### PR TITLE
Exiva # fix

### PR DESCRIPTION
**Pull request by Nrated**
exiva #ITEM ID SLOT - fix for 7.6 OT servers

### CODE REVIEW

**Comment by divinity76** [comment]
another "move 0 items" fix ^^

i believe this is a bug simply not discovered before 861,  but i am too lazy to confirm that suspicion -   also _some_ OT servers accept "move 0", and some OT servers doesn't :o  (and some OT servers even use it as a anticheat, where "move 0" will instantly ban you)

**Comment by divinity76** [comment]
another "move 0 items" fix ^^

i believe this is a bug simply not discovered before 860, but i am too lazy to confirm that suspicion - also some OT servers accept "move 0", and some OT servers doesn't :o (and some OT servers even use it as a anticheat / autodetect , where "move 0" will instantly ban you, like  cafeotsmax )

**Comment by Nrated** [comment]
Oh, I didn't knew that! It was just very annoying to use RAW packets all the time when I or my friends were getting fresh install of blackd ^^

**Comment by divinity76** [comment]
what OTs do you play anyway?

**Comment by Nrated** [comment]
armia.toproste.pl and mazurskiots.pl
could you read your e-mails? I've sent you a question about something

**Pull request merged**
